// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2TrSDdG7h-CJRc8XXRj3veO4HVi4pIic',
    appId: '1:1009642980380:web:5e3a4c6c5fecd8ba3bcbd9',
    messagingSenderId: '1009642980380',
    projectId: 'my-mihir-notes-flutter-project',
    authDomain: 'my-mihir-notes-flutter-project.firebaseapp.com',
    storageBucket: 'my-mihir-notes-flutter-project.appspot.com',
    measurementId: 'G-FN5BXCMH2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvcPqehix3HWP0X3lo8wdIJrR19cu_yM',
    appId: '1:1009642980380:android:d0b7af3cdc2424133bcbd9',
    messagingSenderId: '1009642980380',
    projectId: 'my-mihir-notes-flutter-project',
    storageBucket: 'my-mihir-notes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrp8IG9_EtdJWJ6bHbZxmOjapWBfWmKX0',
    appId: '1:1009642980380:ios:454d7b4c1373d5a93bcbd9',
    messagingSenderId: '1009642980380',
    projectId: 'my-mihir-notes-flutter-project',
    storageBucket: 'my-mihir-notes-flutter-project.appspot.com',
    iosClientId: '1009642980380-1in1o1p85m2c1vnti4g003hbnj8lj7jl.apps.googleusercontent.com',
    iosBundleId: 'com.domain.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrp8IG9_EtdJWJ6bHbZxmOjapWBfWmKX0',
    appId: '1:1009642980380:ios:d63f51e9405ab2b23bcbd9',
    messagingSenderId: '1009642980380',
    projectId: 'my-mihir-notes-flutter-project',
    storageBucket: 'my-mihir-notes-flutter-project.appspot.com',
    iosClientId: '1009642980380-fq5kll0fdraffgs6h4f5ccj8j20t71l1.apps.googleusercontent.com',
    iosBundleId: 'com.domain.mynotes.RunnerTests',
  );
}
